version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: chess-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "40000-40100:40000-40100/udp"
      - "40000-40100:40000-40100/tcp"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=8080
      - ANNOUNCED_IP=${ANNOUNCED_IP}
    volumes:
      - ./logs:/app/logs

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: chess-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://server:8080