# ---- Builder ----
FROM node:20 AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# ---- Runner ----
FROM node:20-slim
WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./

RUN npm install --omit=dev

EXPOSE 8080
EXPOSE 40000-40499/udp
EXPOSE 40000-40499/tcp

CMD ["node", "dist/index.js"]